### ISSUE TITLE
部分组件收费不敢使用

### ISSUE THREAD

**Issue by minxiang51574** [FirstUI/FirstUI#12]
当前项目是uni + vue3 + vite ， 由于要兼容h5，市面上没有合适的组件库（vant的使用小程序与h5使用不一样），在掘进上看到了这个组件库很适合，可惜要收费；可以理解，希望未来能开源，这样更多的人就能用起来了。

**Comment by minxiang51574** [comment]
删除

**Comment by zhuewizz** [comment]
我是付费用户 会员完整的代码如何获得？

**Comment by elarbor** [comment]
个人感觉喜欢 https://github.com/sutras/sard-uniapp
