### ISSUE TITLE
[bug] DatePicker 日期时间选择器在nvue页面多次选择修改默认值后，显示日期不准确

### ISSUE THREAD

**Issue by mingyigg** [FirstUI/FirstUI#13]
页面：nvue
vue版本：vue2
编译平台：安卓
设备：Redmi Note9 
MIUI版本：MIUI 12.5.9
Android版本：11
firstui版本：v1.7.0
现象：设置默认值后，第一次点击正常，选择时间后在回调函数中修改默认值为选中时间，再次点击，显示的时间对不准，比如日这个显示的就不是准确的日期

![IMG_20221004_103608](https://user-images.githubusercontent.com/21259162/193722499-fc462ee5-ca96-405f-9be4-f064f60cdcec.jpg)

关键代码：
`	<fui-date-picker
				:show="startShow"
				:value="startTime"
				type="3"
				:minDate="minDate"
				:confirmText="i18n.confirm"
				:cancelText="i18n.cancel"
				:confirmColor="COLORS.base"
				@change="selectStartTime" 
				@cancel="closeStartTime"></fui-date-picker>`

`
			closeStartTime() {
				this.startShow = false;
			},
			selectStartTime(e) {
				this.startShow = false;
				this.startTime = e.result;
			},`

![760E5A05D340D26A7E52BB12E68CB6AE](https://user-images.githubusercontent.com/21259162/193722693-8222fca1-e94a-473a-84a5-c104a9f0168c.jpg)

![19A8D598E61517C044A51030DCDCB3DA](https://user-images.githubusercontent.com/21259162/193722721-5012fb4b-22c4-469b-bc07-23fb82b6e734.jpg)

**Comment by FirstUI** [comment]
不要将选中的值再次赋值给默认值，默认值一般仅初始化使用

**Comment by mingyigg** [comment]
> 不要将选中的值再次赋值给默认值，默认值一般仅初始化使用

嗯嗯，不再次赋值给默认值确实可以解决这个问题。但是我这个每次修改默认值也是有使用场景的，比如我有个场景是，让用户设置N个提醒，每个提醒都是一个时间选择器，用户设置完成后，有可能再次点开页面，去修改每个时间选择器的时间，还有可能新增时间选择器，这样的话我要有两个数组，一个数组用来保存默认值，一个用来保存选中值，真的很麻烦。不知道你们能否支持一下我这个场景，修改默认值，再次点开就是默认值设置的那个时间点
