### ISSUE TITLE
在某些组件的初始化中，boundingClientRect方法出现的问题

### ISSUE THREAD

**Issue by Wzixiao** [FirstUI/FirstUI#24]
在我查看/使用（如rate）一些组件时，mounted中以下代码返回值有可能会出现不可被使用（不被正常逻辑认可）的情况

```javascript
uni.createSelectorQuery().in(this)..select('xxx').boundingClientRect().exec(callback)
```

普遍做法是使用timeout（并且我已经发现一些组件是这样做的），但是效果可能不太理想，是否可以使用updated代替mounted？因为在一些数据没有被页面使用时，不会导致页面二次刷新。又或者在timeout中的方法再次使用timeout（0）来重新规划时间片，来避免此问题发生？

**Comment by FirstUI** [comment]
下个版本排查一下所有组件，做一下优化
