### ISSUE TITLE
fui-checkbox组件的value只能支持string，不能支持number

### ISSUE THREAD

**Issue by dmdoit** [FirstUI/FirstUI#29]
fui-checkbox组件的value只能支持string，不能支持number，需要支持number，不然控制台报很多警告
![image](https://github.com/FirstUI/FirstUI/assets/19385704/a3daa1bb-9aac-45f5-b7ff-e08b6a2c7e3c)

**Comment by FirstUI** [comment]
暂时可以先转化一下再传入，后期优化一下
