### ISSUE TITLE
如果能使用iconify图标就好了

### ISSUE THREAD

**Issue by elarbor** [FirstUI/FirstUI#31]
这UI确实挺不错，接入简单，不像uview如要配置四五个地方。而且也能给组件class，真不错，uview就不能
![image](https://github.com/FirstUI/FirstUI/assets/43592730/723a29f7-4e26-4265-9d1e-dc45c0ff473a)

重点是我引入了unocss，居然不报错。uview报错报到我以为uniapp就不能引😂
![image](https://github.com/FirstUI/FirstUI/assets/43592730/4a134b5c-ae64-4e32-b8db-b8c17d79db7f)

**Comment by FirstUI** [comment]
已记录
