### ISSUE TITLE
付费版国际化组件，h5正常，安卓App白屏报错

### ISSUE THREAD

**Issue by PandaBalls** [FirstUI/FirstUI#38]
`Uncaught TypeError: Cannot read property 'userAgent' of undefined`

不知道为什么，是不是国际化部分错误，i28n依赖的错误么。
用的vue3的proxy获取i28n在script里面使用。

**Comment by FirstUI** [comment]
排查一下看看是不是这块出现的错误，怎么使用的，参考一下他们这个文档看看：https://uniapp.dcloud.net.cn/tutorial/i18n.html
