### ISSUE TITLE
BottomPopup组件为什么是苹果手机时候要加padding-bottom: 34px;

### ISSUE THREAD

**Issue by Ya-hui** [FirstUI/FirstUI#4]
如题

我看BottomPopup组件的代码在iphone机型的时候会加个padding-bottom: 34px; 不知道为什么要加他呢？ 
那样苹果机 底部不就要空白一段了吗？

<img width="676" alt="image" src="https://user-images.githubusercontent.com/13138164/158020627-f00e9f52-6e84-47c6-9762-5668ef8b71a1.png">
<img width="855" alt="image" src="https://user-images.githubusercontent.com/13138164/158020637-728fa365-1a20-469c-86d2-127fe7321910.png">

**Comment by FirstUI** [comment]
安全区域距离底部边界距离

**Comment by Ya-hui** [comment]
但是底部的tabbar 本身已经做了安全区域的适配呀

**Comment by FirstUI** [comment]
后面增加个属性控制一下
