### ISSUE TITLE
badge组件建议新增max参数来控制

### ISSUE THREAD

**Issue by LiXunGuan** [FirstUI/FirstUI#5]
建议新增max参数
最大值，超过最大值会显示 '{max}+'
![1648361929(1)](https://user-images.githubusercontent.com/7980846/160269271-00baf1d2-5d8c-43cd-86b8-8dcae0e0f689.png)

```
<fui-badge :absolute="true" type="danger" :value="150" :max="99"></fui-badge>
```

**Comment by FirstUI** [comment]
已优化
